<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="./../global.cs" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
	  <PackageReference Include="OpenCvSharp4.official.runtime.linux-x64.slim" Version="4.13.0.20260627" />
	  <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MangaBox.Match\MangaBox.Match.csproj" />
		<ProjectReference Include="..\MangaBox.Utilities.Flare\MangaBox.Utilities.Flare.csproj" />
	</ItemGroup>

</Project>
