CREATE TABLE IF NOT EXISTS mb_lists (
	id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	profile_id UUID NOT NULL REFERENCES mb_profiles(id),
	name TEXT NOT NULL,
	description TEXT NULL,
	is_public BOOLEAN NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL,
	CONSTRAINT mb_lists_unique UNIQUE NULLS NOT DISTINCT (profile_id, name)
);
