CREATE TABLE IF NOT EXISTS mb_list_ext (
	id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	list_id UUID NOT NULL UNIQUE NULLS NOT DISTINCT REFERENCES mb_lists(id),
	cover_id UUID NULL REFERENCES mb_images(id),
	manga_count INTEGER NOT NULL,
	cloned_count INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);