CREATE TABLE IF NOT EXISTS mb_people (
	id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	name TEXT NULL UNIQUE NULLS NOT DISTINCT,
	avatar TEXT NULL,
	artist BOOLEAN NOT NULL,
	author BOOLEAN NOT NULL,
	is_user BOOLEAN NOT NULL,
	profile_id UUID NULL REFERENCES mb_profiles(id),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);
