CREATE TABLE IF NOT EXISTS mb_sources (
	id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	slug TEXT NOT NULL UNIQUE,
	base_url TEXT NOT NULL,
	is_hidden BOOLEAN NOT NULL,
	enabled BOOLEAN NOT NULL,
	referer TEXT NULL,
	user_agent TEXT NULL,
	headers mb_headers[] DEFAULT '{}',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);
