CREATE TABLE IF NOT EXISTS mb_tags (
	id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	name TEXT NULL UNIQUE NULLS NOT DISTINCT,
	description TEXT NULL,
	source_id UUID NOT NULL REFERENCES mb_sources(id),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL
);
