CREATE TABLE IF NOT EXISTS mb_request_log (
	id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	
	profile_id UUID,
	start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	end_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	url TEXT NOT NULL,
	code INTEGER NOT NULL,
	body TEXT,
	stack_trace TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP
);