CREATE TABLE IF NOT EXISTS mb_tags (
	id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	
	name TEXT NOT NULL UNIQUE,
	display TEXT NOT NULL,
	explicit BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by UUID NOT NULL REFERENCES mb_people(id),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_by UUID NOT NULL REFERENCES mb_people(id),
	deleted_at TIMESTAMP,
	deleted_by UUID REFERENCES mb_people(id)
);